1st push
drumer32/explorewithme pull request #1
Opened 2022-09-26 03:00 UTC by drumer32

2022-09-26 15:56 UTC, eugene-lenkevich requested changes
Привет, Георгий, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошел до дипломной работы, ты крут без вариантов :)

Далее, наша цель в том, чтобы сделать красоту в этом проекте, я оставил кучку коментариев. 

В первую очередь. У меня  сборка не проходит, вижу что потому что не настроены тесты, но их и не требуют в этом задании, потому лучше или убрать тесты или починить(если время будет). Кто то скачает проект а у него он не соберется, это как то не гут :)

В общем, надо сделать конфетку, будут вопросы, задавай в слаке, не стесняйся, немножко допилить осталось :)

PS 
пакеты, кстати, более канонично (так очень часто на проектах бывает) будут выглядеть вот в такой струкуре
-базовый пакет
 -- model
 -- service
 -- controller
 -- configuration
 -- dto
если будет желание можешь сделать примерно так же :)

Удачи!

2022-09-26 15:56 UTC, eugene-lenkevich commented on server/src/main/java/com/drumer32/explorewithme/service/CategoryServiceImpl.java
> +            return categoryStorage.findById(id).get();
categoryStorage.findById(id).orElseThrow(()-> new ObjectNotFound....)

Покороче чутка :)

2022-09-26 15:56 UTC, eugene-lenkevich commented on server/src/main/java/com/drumer32/explorewithme/service/EventServiceImpl.java
> +        for (Integer id : userId) {
Вот тут, кстати, для каждого userId, насколько понимаю будет выполнен отдельный запрос к БД, что может быть достаточно накладно. Мы же можем вытащить все сущности за один раз 

eventStorage.findAllByInitiatorIn(List<Long>, customPageable)

2022-09-26 15:56 UTC, eugene-lenkevich commented on server/src/main/java/com/drumer32/explorewithme/service/EventServiceImpl.java
> +        for (Event event : eventStorage.getEventByInitiator(userId, pageable).getContent()) {
Опять таки, можно все данные выгрести одним запросом :)

2022-09-26 15:56 UTC, eugene-lenkevich commented on server/src/main/java/com/drumer32/explorewithme/service/EventServiceImpl.java
> +        events.removeIf(event -> (!state.contains(event.getState())) & (!categories.contains(event.getCategory())) &
А нельзя ли эту фильтрацию перенести на уровень БД, сконструировать соответсвующий запрос в @Query

2022-09-26 15:56 UTC, eugene-lenkevich commented on server/src/main/java/com/drumer32/explorewithme/service/RequestServiceImpl.java
> +        } catch (NullPointerException e) {
А он точно тут выкинет NullPointerException а не пустой список?

Во вторых, NPE не надо ловить, вооще, это непроверяемое исключение означает, что в алгоритме допущена ошибка :)

2022-09-26 15:56 UTC, eugene-lenkevich commented on server/src/main/java/com/drumer32/explorewithme/service/RequestServiceImpl.java
> +            return requestStorage.findById(id).get();
return requestStorage.findById(id).orElseThrow...

2022-09-26 15:56 UTC, eugene-lenkevich commented on server/src/main/resources/schema.sql
> +    status VARCHAR(512)                           NOT NULL,
А на статус точно надо 512 символов, может помешьше хваит? :)

2022-09-26 15:56 UTC, eugene-lenkevich commented on server/src/main/resources/schema.sql
> +    description        VARCHAR(255),
Мне кажется что на поле описание не хватит 255 символов, лучше тут сделать тип varchar(4000), например, а еще лучше - text

description        TEXT,

2022-09-26 23:36 UTC, drumer32 commented on server/src/main/resources/schema.sql
> +    status VARCHAR(512)                           NOT NULL,
Это была автогенерация, не уследил)

2022-09-27 02:03 UTC, drumer32 commented on server/src/main/java/com/drumer32/explorewithme/client/EventClient.java
> +    public EventClient(@Value("http://localhost:9090") String serverUrl, RestTemplateBuilder builder) {
крутил вертел весь вечер, понимаю, что мы задаем конфиг и передаем в EventClient, но дельного ничего не выходит

2022-09-27 02:12 UTC, drumer32 commented on server/src/main/java/com/drumer32/explorewithme/controller/isadmin/AdminUserController.java
> +    Collection<User> getAll(@RequestParam(value = "ids") List<Integer> userId,
у меня нигде контроллеры не возвращают Page, их возвращают репозитории, мне с листами проще работать

2022-09-27 02:14 UTC, drumer32 commented on server/src/main/java/com/drumer32/explorewithme/controller/isadmin/AdminEventController.java
> +                                           @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
вроде получилось)

2022-09-27 02:53 UTC, drumer32 commented on server/src/main/java/com/drumer32/explorewithme/service/EventServiceImpl.java
> +        events.removeIf(event -> (!state.contains(event.getState())) & (!categories.contains(event.getCategory())) &
сделал сложный запрос. не очень люблю query)

2022-09-27 03:17 UTC, drumer32 commented
Евгений, здравствуйте! Большое спасибо за ревью! Очень рад, что Вы снова мой ревьюер! Также рад, что Вам понравилось. Не идеально, конечно, но стараюсь изо всех сил)
- Сборку починил. Действительно, пустой тест contextLoad все запорол. Теперь все крутится-вертится как надо.

- Насчет структуры пакетов я решил поэкспериментировать. В прошло проекте у нас была сортировка по имени класса (User, Booking, Item и тд.) В этот раз я решил вернуться к сортировке по функционалу. Проверить так сказать. Убедился, что предыдущий вариант был поудобнее ) Но для это проекта решил оставить так, а то вдруг все развалится)

 - Конфиг с ModelMapper вроде понял, с EventClient не выходит, хотя теоретически я понимаю что нужно.
 
Ещё раз большое спасибо!

2022-09-27 05:40 UTC, eugene-lenkevich commented
> * Сборку починил. Действительно, пустой тест contextLoad все запорол. Теперь все крутится-вертится как надо.

Успешная сборка, да вообще красота, тут самое важное :)

> * Насчет структуры пакетов я решил поэкспериментировать. В прошло проекте у нас была сортировка по имени класса (User, Booking, Item и тд.) В этот раз я решил вернуться к сортировке по функционалу. Проверить так сказать. Убедился, что предыдущий вариант был поудобнее ) Но для это проекта решил оставить так, а то вдруг все развалится)

Ну я просто предложил, но в целом верно, да, есть разные подходы, главное чтобы это все было осознанно :)

> * Конфиг с ModelMapper вроде понял, с EventClient не выходит, хотя теоретически я понимаю что нужно.

Давай разбираться :)
Конфиг не надо никуда инжектить, по сути они нужны только при запуске, спринг при запуске контекста их собирает, с помощью них создает нужные бины и уже их инжектит куда надо. 
То есть, с маппером можно вот так

![image](https://user-images.githubusercontent.com/94845100/192440397-4d1bbd3f-fb11-4e97-8562-c4e7f6b635d8.png)

По крайней мере контекст стартует, спасибо кстати что оставил конфимгурацию с h2-базой данных, я на ней запустился :)
![image](https://user-images.githubusercontent.com/94845100/192440599-0b59896e-0b72-4241-95e4-46908d95e6fa.png)

![image](https://user-images.githubusercontent.com/94845100/192440663-7f89db53-a680-4e16-9468-68570012231c.png)


Далее, web-client.

Сперва наперво я убрал с него все спринговые аннотации и переделал конструктор

![image](https://user-images.githubusercontent.com/94845100/192440834-8bf4ae5c-5df5-435a-8525-851be2172df6.png)

Далее, вынес все конфигурирование в конфигурацию

![image](https://user-images.githubusercontent.com/94845100/192441047-9ba94718-2225-4181-9fe2-1550a48fe34e.png)

А дальше все точно так же инжектится (как и было, в общем то)

![image](https://user-images.githubusercontent.com/94845100/192441589-762a6015-510d-4dbf-a789-f4651a2ebe18.png)

2022-09-27 05:49 UTC, eugene-lenkevich requested changes
Привет, спасибо за правки, оставил коментарий по конфигурациям, надеюсь получилось пояснить, но если что спрашивай :)

2022-09-27 06:38 UTC, drumer32 commented
я понял! )))) мы просто на стороне делаем конфиг с настройками, а условный mapper импортируем в классах пустой, как будто без настроек. и по ходу пьесы спринг подгрузит наш бин-конфиг и mapper заработает как надо

с eventClient я себе что то такое и представлял, но не понимал как бин собрать правильно.

2022-09-27 07:21 UTC, eugene-lenkevich approved these changes
Ага, именно так оно и работает :) 
Теперь все норм, спасибо!

2022-09-27 07:30 UTC, drumer32 commented
Блин, круто! После сегодняшнего у меня прям четкое понимание всего этого сложилось. Спасибо за такое подробное объяснение🙂 

И ещё раз хочу поблагодарить Вас за все-все ревью, практически год работаем вместе! Супер легко нашли общий язык, все супер понятно и комфортно! Будущим ревьюерам будет на кого равняться ) Даже грустно немного, но видимо на этом все..
Огромное спасибо!

2022-09-27 20:21 UTC, merged